### ISSUE TITLE
Template writes fail w/o matching TemplateProperty

### ISSUE THREAD

**Issue by achavez** [DallasMorningNews/django-chartwerk#15]
The template properties don't have fixtures, but their tags exist in the fixtures for the templates (I think):

```json
{
  ...
  "template": {
    ...
    "tags": ["map"]
  }
}
```

That means that the template-related API endpoints fail at https://github.com/DallasMorningNews/django-chartwerk/blob/f3177112bab63bd31a0f730495218146432fbcde/chartwerk/serializers.py#L39-L42

I'm thinking we can just ignore cases where a `TemplateProperty` doesn't exist, because that could happen for a lot of reasons, right?

**Comment by hobbes7878** [comment]
Yes, since we're saving template tags in blob JSON, there is no inherent integrity to the relationship if say a template tag gets deleted. Two things to do for now:

1. Add a try statement to create and update serializer methods
2. Remove template tags from fixtures

Then I need to think about how to handle the case where a template tag gets deleted. I think the easiest would be to set template tags to null in the serializer on save, but I'd still have to traverse a little JSON which is kinda ick...
